### ISSUE TITLE
Merge into main moveit repo

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_kinematics_tests#12]
I'd like to see this repo get merged into the main moveit repo. The main obstacle is whether adding these additional tests would slowdown the CI build too much (beyond the timeout). This is a technical problem, but we should figure out a way to overcome it for better testing coverage.

**Comment by jrgnicho** [comment]
If we can get around the timeout issue I'm OK with merging it there.  The support packages should probably be moved to moveit_resources.

**Comment by davetcoleman** [comment]
I just emailed Travis support to see if there is a way to increase it. Overall, I think we could still merge this repo because we currently average 38 min and the max is 50 min for the .org (open source) version of Travis. The paid version is 120 fyi.

**Comment by jrgnicho** [comment]
Cool, I'm on board with merging.  This last [PR](https://travis-ci.org/ros-planning/moveit_kinematics_tests/builds/252658168) only took 7 min 38 secs.  
Will this be just a direct copy into the moveit repo?

**Comment by davetcoleman** [comment]
TravisCI:

> We have increased the maximum timeout for the ros-planning/moveit repository to 70 minutes, please let us know if that would be enough.
> We have had a look at the build log of one of your builds, and we are not sure how to make it faster. The majority of the time is spent inside the docker container. A part of that time is building the application, and another part is running the tests. We suspect that you might be able to gain some valuable time by caching the build artifacts. One way of doing that, would be to make use of ccache.
> This will require some setup, of course, and I am not completely sure how much time is being spent in the building itself.

hurray!

As for how to merge it - I would like to actually move most of the moveit_config packages, URDFs, and meshes into [moveit_resources](https://github.com/ros-planning/moveit_resources) and move the tests into [moveit_kinematics](https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_kinematics) in the main moveit repo. So we would just copy-paste these things and keep this repo around for the next few years in case we need the commit history. This would add these tests to our main build automatically, improving test coverage and simplifying code locations.

**Comment by jrgnicho** [comment]
@davetcoleman I think splitting this repo as you suggested makes sense.  I just noticed there's a pending license issue #8, maybe it no longer is an issue since it'll get moved.

**Comment by davetcoleman** [comment]
Please resolve the license issue since they are your commits

**Comment by davetcoleman** [comment]
Now that https://github.com/ros-planning/moveit_kinematics_tests/pull/14 is merged I think we can split this repo. @jrgnicho do you still have cycles for this?

**Comment by jrgnicho** [comment]
@davetcoleman I do not have any changes coming up.  We should be ready to split this now, I'll get started on that this weekend.  I don't know if it makes sense to copy the entire **kinematics_test** package into moveit or just the one source file into the kinematics package in moveit?

**Comment by davetcoleman** [comment]
I think all the robot test setups, packages, and resources belong in moveit_resources and yes, just the test belongs in moveit main.

**Comment by davetcoleman** [comment]
@jrgnicho note that we have a new UR3 IK test that will be added hopefully soon, too: https://github.com/ros-planning/moveit/pull/612/files

**Comment by jrgnicho** [comment]
I have started this today, however I'm not sure where to place the ikfast_plugin code.  At first I thought of copying the cpp files into moveit_resources but it looks like that package is meant to hold just resource files and no code whatsoever.  Any suggestions?

**Comment by davetcoleman** [comment]
moveit_resources is a perfect place to store example ikfast auto-generated code used in tests - that repo is intended for test assets just like this.

**Comment by davetcoleman** [comment]
@jrgnicho what is the status of this? it would be great to merge this in before https://github.com/ros-planning/moveit/pull/725 since we need these tests to verify @rhaschke's changes

**Comment by davetcoleman** [comment]
I believe this issue can be closed now that @rhaschke finished https://github.com/ros-planning/moveit/pull/1272

In addition, I will mark this repo as DEPRECATED and "archive" the repo (freeze it) similar to https://github.com/ros-planning/moveit_ros

Any objections?

**Comment by davetcoleman** [comment]
Archiving this repo now...
