### ISSUE TITLE
Purpose/how to use this repo

### ISSUE THREAD

**Issue by jonbinney** [moveit/moveit_kinematics_tests#4]
@davetcoleman pointed this repo out to me, and I'm very excited about the ability to test kinematics on multiple robots in an automated way.

My use case is that I want to modify kinematics plugins, then test them on multiple different robots with multiple different pose goals. Is that the purpose of this repo @jrgnicho ? Given the name of the repo, I expected to see rostests or rosunit tests that verify plugin behavior - is that the intention? Also, why are there actual kinematic plugins in this repo? Shouldn't there just be tests?

Final question: is the dependency on pr2_moveit_config a good one? (I think) that the pr2 stuff tends to be ported to new rosdistros fairly late, and I'd rather not have to wait for that before using moveit_kinematics_tests to test moveit on kinetic.

**Comment by davetcoleman** [comment]
Another question: has this actually been used across three different branches I/J/K? 

Also, I noticed the rosinstall file needs to be updated to the consolidated repo

**Comment by jrgnicho** [comment]
Sorry for the late reply, I was on travel
@jonbinney the purpose of this repo is to test that changes to the `kinematics::KinematicsBase` interface don't brake existing specializations of it (ikfast, pr2 kinematics, universal custom kinematics, etc).  There was a significant [API change](https://github.com/ros-planning/moveit_core/pull/248) accross multiple repositories a while back, thus we needed the kinematics plugins to test these changes as the `kinematics::KinematicsBase` can not be tested by itself.  
- There is a [gtest](https://github.com/ros-planning/moveit_kinematics_tests/blob/kinetic-devel/kinematics_base_test/src/test_kinematics_plugin.cpp#L500) in this repo which can be configured to run any kinematics plugin by as shown here for the [motoman sia20d arm](https://github.com/ros-planning/moveit_kinematics_tests/blob/kinetic-devel/kinematics_base_test/launch/test_ikfast_w_redundancy_plugin.launch). From what you described it should serve your use-case
- The pr2 stuff is only needed to load the pr2 resources and can be easily removed.

@davetcoleman the gtest has only been run on indigo very thoroughly and jade to a limited extent.

**Comment by davetcoleman** [comment]
@jrgnicho do you think we can merge the test into the main moveit repo? Any assets (meshes) would need to go into moveit_resources

**Comment by davetcoleman** [comment]
This has been migrated into the main moveit repo, closing.
