### ISSUE TITLE
<license>TODO</license> any decision so far?

### ISSUE THREAD

**Issue by alex-gee** [moveit/moveit_kinematics_tests#8]
Hi! Is it possible to define the license of moveit_kinematics_tests/kinematics_base_test/? Great package for getting started with automated kinematics tests. Thanks for the contribution!

**Comment by jrgnicho** [comment]
@alex-gee thanks for bringing this up.  The license should be BSD (mirroring [ Moveit's](https://github.com/ros-planning/moveit/blob/kinetic-devel/LICENSE.txt)).  I'll try and get that added this week.  
@davetcoleman I'm not sure what the organization name in the license file should be, any thoughts?  (MoveIt's license still says Willow Garage)

**Comment by davetcoleman** [comment]
Most of the commits are yours, so I'd use SwRI or ROS-I

**Comment by davetcoleman** [comment]
@jrgnicho can you do a quick PR to cleanup the license and org name to BSD and SwRI?

**Comment by davetcoleman** [comment]
Fixed by https://github.com/ros-planning/moveit_kinematics_tests/pull/14
